USE [master]
GO

/****** Object:  Database [SCHON]    Script Date: 07/20/2010 21:22:49 ******/
CREATE DATABASE [SCHON] ON  PRIMARY 
( NAME = N'SCHON', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\SCHON.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SCHON_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\SCHON_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SCHON] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SCHON].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SCHON] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SCHON] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SCHON] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SCHON] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SCHON] SET ARITHABORT OFF 
GO

ALTER DATABASE [SCHON] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SCHON] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [SCHON] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SCHON] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SCHON] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SCHON] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SCHON] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SCHON] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SCHON] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SCHON] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SCHON] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SCHON] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SCHON] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SCHON] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SCHON] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SCHON] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SCHON] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SCHON] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SCHON] SET  READ_WRITE 
GO

ALTER DATABASE [SCHON] SET RECOVERY FULL 
GO

ALTER DATABASE [SCHON] SET  MULTI_USER 
GO

ALTER DATABASE [SCHON] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SCHON] SET DB_CHAINING OFF 
GO


